config/routes.rb
Sal7711Gen::Engine.routes.draw do

  get 'buscar/:id', to: 'buscar#mostraruno', as: 'buscar_mostraruno'
  get 'buscar' => 'buscar#index', as: 'buscar'
  get 'mundep' => 'buscar#mundep', as: 'buscar_mundep'
  get 'codigo' => 'admin/categoriaprensa#busca', as: 'categoriaprensa_busca'
  get 'articulos' => 'buscar#index', as: 'articulos'
  get 'bitacorausuario' => 'bitacora#usuario', as: 'bitacora_usuario'

  get "articulos/nuevo" => 'articulos#new'
  get "articulos/:id" => 'buscar#redirigeindex'

  resources :articulos, path_names: { new: 'nuevo', edit: 'edita' },
    only: [:edit, :update, :new, :create, :destroy]
  

  namespace :admin do
    ab = ::Ability.new
    ab.tablasbasicas.each do |t|
      if (t[0] == "Sal7711Gen") 
        c = t[1].pluralize
        resources c.to_sym, 
          path_names: { new: 'nueva', edit: 'edita' }
      end
    end
  end

end

app/models/sal7711_gen/ability.rb
module Sal7711Gen
	class Ability  < Msip::Ability

    BASICAS_PROPIAS = [
      ['Sal7711Gen', 'categoriaprensa']
    ]
    def tablasbasicas 
      Msip::Ability::BASICAS_PROPIAS + BASICAS_PROPIAS - [
        ['Msip', 'centropoblado'],
        ['Msip', 'etiqueta'],
        ['Msip', 'grupo'],
        ['Msip', 'oficina'],
        ['Msip', 'perfilorgsocial'],
        ['Msip', 'sectororgsocial'],
        ['Msip', 'tcentropoblado'],
        ['Msip', 'tdocumento'],
        ['Msip', 'trelacion'],
        ['Msip', 'trivalente'],
        ['Msip', 'tsitio']
      ] 
    end

    BASICAS_ID_NOAUTO = []
    # Hereda basicas_id_noauto de msip
   
    NOBASICAS_INDSEQID =  []
    # Hereda nobasicas_indice_seq_con_id de msip
   
    BASICAS_PRIO = []
    # Hereda tablasbasicas_prio de msip


    # Se definen habilidades con cancancan
    # Util en motores y aplicaciones de prueba
    # En aplicaciones es mejor escribir completo el modelo de autorización
    # para facilitar su análisis y evitar cambios inesperados al actualizar
    # motores
    # @usuario Usuario que hace petición
    def initialize_sal7711_gen(usuario = nil)
      initialize_msip(usuario)
      if usuario && usuario.rol then
        can :read, Sal7711Gen::Articulo
        case usuario.rol 
        when Ability::ROLANALI
        when Ability::ROLADMIN
          can :manage, Sal7711Gen::Articulo
        end
      end
    end

  end
end

app/models/sal7711_gen/anexo_articulo.rb
module Sal7711Gen
  class AnexoArticulo < ActiveRecord::Base
    belongs_to :anexo, class_name: 'Msip::Anexo', 
      foreign_key: 'anexo_id', optional: false
    belongs_to :articulo, 
      class_name: 'Sal7711Gen::Articulo', 
      foreign_key: 'articulo_id', optional: false
  end
end

app/models/sal7711_gen/articulo.rb
require 'sal7711_gen/concerns/models/articulo'

module Sal7711Gen
  class Articulo < ActiveRecord::Base
    include Sal7711Gen::Concerns::Models::Articulo
  end
end

app/models/sal7711_gen/articulo_categoriaprensa.rb
module Sal7711Gen
  class ArticuloCategoriaprensa < ActiveRecord::Base
    belongs_to :articulo, class_name: 'Sal7711Gen::Articulo', 
      foreign_key: 'articulo_id', optional: false
    belongs_to :categoriaprensa, 
      class_name: 'Sal7711Gen::Categoriaprensa', 
      foreign_key: 'categoriaprensa_id', optional: false
  end
end

app/models/sal7711_gen/bitacora.rb
module Sal7711Gen
  class Bitacora < ActiveRecord::Base

    include Msip::Localizacion

    serialize :detalle, coder: YAML
    belongs_to :usuario, foreign_key: 'usuario_id',
      validate: true, class_name: 'Usuario', optional: false

    campofecha_localizado :fecha

    def self.a(ip, usuario, operacion, detalle, detalle2 = nil, 
               detalle3 = nil)
      operacion = operacion ? operacion.to_s : ''
      operacion = operacion[0..49] if operacion && operacion.length > 50
      detalle2 = detalle2 ? detalle2.to_s : ''
      detalle2 = detalle2[0..499] if detalle2 && detalle2.length > 500
      detalle3 = detalle3 ? detalle3.to_s : ''
      detalle3 = detalle3[0..499] if detalle3 && detalle3.length > 500
      b = Bitacora.new(
        fecha: Time.now.utc.iso8601,
        ip: ip.to_s,
        usuario_id: usuario.id,
        operacion: operacion.to_s,
        detalle: detalle.to_s,
        detalle2: detalle2.to_s,
        detalle3: detalle3.to_s
      )
      if b.detalle && b.detalle.to_yaml.length > 5000
       b.detalle = b.detalle.to_yaml[0..4000]
      end
      b.save!
    end
  end
end

app/models/sal7711_gen/categoriaprensa.rb
require 'sal7711_gen/concerns/models/categoriaprensa'

module Sal7711Gen
  class Categoriaprensa < ActiveRecord::Base
    include Sal7711Gen::Concerns::Models::Categoriaprensa
  end
end

app/controllers/sal7711_gen/admin/categoriasprensa_controller.rb
module Sal7711Gen
  module Admin
    class CategoriasprensaController < Msip::Admin::BasicasController
      before_action :set_categoriaprensa, 
        only: [:show, :edit, :update, :destroy]
      load_and_authorize_resource  class: Sal7711Gen::Categoriaprensa

      def clase 
        "Sal7711Gen::Categoriaprensa"
      end

      def camponombre
        :codigo
      end

      def set_categoriaprensa
        @basica = Categoriaprensa.find(params[:id])
      end

      def atributos_index
        [
          "id", 
          "codigo", 
          "nombre", 
          "observaciones", 
          "fechacreacion_localizada", 
          "habilitado"
        ]
      end

      def categoriaprensa_params
        params.require(:categoriaprensa).permit(*atributos_form)
      end

    end
  end
end

app/controllers/sal7711_gen/articulos_controller.rb
require 'sal7711_gen/concerns/controllers/articulos_controller'

module Sal7711Gen
  class ArticulosController < Msip::ModelosController
 
    before_action :set_articulo, only: [:edit, :update, :destroy]
    load_and_authorize_resource class: Sal7711Gen::Articulo
    include Sal7711Gen::Concerns::Controllers::ArticulosController    

  end
end

app/controllers/sal7711_gen/bitacora_controller.rb
require 'sal7711_gen/concerns/controllers/bitacora_controller'

module Sal7711Gen
  class BitacoraController < ApplicationController
 
    load_and_authorize_resource class: Sal7711Gen::Bitacora
    include Sal7711Gen::Concerns::Controllers::BitacoraController    
  
  end
end

app/controllers/sal7711_gen/buscar_controller.rb
require 'sal7711_gen/concerns/controllers/buscar_controller'

module Sal7711Gen
  class BuscarController < ApplicationController

    # Autorizacion se hace en detalle por posibilidad de autorizacion por IP
    include Sal7711Gen::Concerns::Controllers::BuscarController    

  end
end

app/controllers/sal7711_gen/hogar_controller.rb
module Sal7711Gen
  class HogarController < Msip::HogarController

    # Sin definir autorizacion porque es para no autenticados
    
    def index
      render layout: 'application'
    end

  end
end

app/helpers/sal7711_gen/application_helper.rb
module Sal7711Gen
  module ApplicationHelper

    include Msip::PaginacionAjaxHelper

    def desc_bitacora(entrada)
      r = ''
      if !entrada[:buscar]
        return ''
      end
      if ( (entrada[:buscar]['fechaini']  && entrada[:buscar][:fechaini] != '') ||
         (entrada[:buscar]['fechafin'] && entrada[:buscar]['fechafin'] != '') )
        r += "Fecha: #{entrada[:buscar]['fechaini']} - " +
          "#{entrada[:buscar]['fechafin']}. "
      end
      if (entrada[:buscar]['mundep'] && entrada[:buscar]['mundep'] != '')
        r += "Muncipio/Departamento: #{entrada[:buscar]['mundep']}. "
      end
      if (entrada[:buscar]['categoria'] && entrada[:buscar]['categoria'] != '')
        r += "Categoria: #{entrada[:buscar]['categoria']}. "
      end
      if (entrada[:buscar]['fuente'] && entrada[:buscar]['fuente'] != '')
        f = Msip::Fuenteprensa.find(entrada[:buscar]['fuente'])
        if f
          r += "Fuente: #{f.nombre}. "
        end
      end
      if  (entrada[:buscar]['pagina'] && entrada[:buscar]['pagina'] != '')
        r += "Página: #{entrada[:buscar]['pagina']}. "
      end
      
      return r
    end

    def buscar_mostraruno(id)
      Rails.configuration.relative_url_root + "buscar/#{id.to_s}"
    end

    # Retorna datos del articulo con la id dada en un vector con:
    # 0- titulo
    # 1- texto
    # 2- rlocal Ruta a fuente (e.g TIF) en sistema de archivos
    # 3- rutajpg Pathname al jpg en colchón en sistema de archivos
    # 4- urljpg Pathname con url relativo al jpg de colchón
    # 5- rutapdf Pathname al pdf en colchón en sistema de archivos
    # 6- urlpdf Pathname con url relativo al pdf en colchón
    def datos_articulo(id) 
      a = Articulo.where("sal7711_gen_articulo.id = ?", id).take
      rlocal = Pathname.new(a.ruta_articulo)
      rutapublic = Rails.root.join('public')
      urlcolchon = Rails.application.config.x.url_colchon.to_s
      rutacolchon = rutapublic.join(urlcolchon)
      if (!File.exist? rutacolchon.to_s)
        raise "Crear directorio #{rutacolchon.to_s}"
      end
      titulo = a.adjunto_descripcion
      texto = a.texto
      anioc = a.created_at.year
      mesc = a.created_at.month
      diac = a.created_at.day
      if titulo.nil?
        byebug
      end
      nomar = titulo.gsub(/[^0-9A-Za-z.\-]/, '_')  + "-" + id.to_s
      rutaf = "#{anioc.to_i.to_s}/#{mesc.to_i.to_s}/#{diac.to_i.to_s}/" 
      rutajpg = rutacolchon.join(rutaf, nomar + '.jpg')
      urljpg = Pathname.new(Rails.configuration.relative_url_root).join(urlcolchon.to_s).join(rutaf, nomar + '.jpg')
      rutapdf = rutacolchon.join(rutaf, nomar + '.pdf')
      urlpdf = Pathname.new(Rails.configuration.relative_url_root).join(urlcolchon.to_s).join(rutaf, nomar + '.pdf')
      return [titulo, texto, rlocal,
              rutajpg, urljpg.to_s, 
              rutapdf, urlpdf.to_s]
    end

    def url_descarga_jpg(id)
      titulo, texto, rlocal, rutajpg, urljpg, rutapdf, urlpdf =
        datos_articulo(id) 
      return urljpg
    end


    # Prepara JPG y PDF para visualizar articulo con la identificación dada
    # y retornar información del mismo
    def prepara_imagenes(id)
      titulo, texto, rlocal, rutajpg, urljpg, rutapdf, urlpdf = 
        datos_articulo(id)
      # Genera JPG
      if !File.exist? "#{rutajpg.to_s}"
        FileUtils.mkdir_p rutajpg.dirname
        system('convert', '-append', rlocal.to_s, rutajpg.to_s)
      end
      if !File.exist? "#{rutajpg.to_s}"
        flash[:error] = "No fue posible convertir #{rlocal}"
        render inline: "No fue posible convertir #{rlocal}"
        return
      end
      # Genera PDF
      if !File.exist? "#{rutapdf.to_s}"
        cmd = "rm -rf /tmp/_sal7711_cinep_mp*"
        puts cmd
        system(cmd)
        cmd = "/usr/local/bin/convert #{rlocal} /tmp/_sal7711_cinep_mp-%d.jpg"
        puts cmd
        system(cmd)
        jpgs = Dir.glob('/tmp/_sal7711_cinep_mp-*jpg')
        FileUtils.mkdir_p rutapdf.dirname
        Prawn::Document.generate("#{rutapdf.to_s}") do
          font_families.update("Tuffy" => {
            :normal => Msip::Engine.root.join('app', 'assets', 'fonts', 'tuffy', 'Tuffy.ttf'),
            :italic => Msip::Engine.root.join('app', 'assets', 'fonts', 'tuffy', 'Tuffy_Italic.ttf'),
            :bold => Msip::Engine.root.join('app', 'assets', 'fonts', 'tuffy', 'Tuffy_Bold.ttf'),
            :bold_italic => Msip::Engine.root.join('app', 'assets', 'fonts', 'tuffy', 'Tuffy_Bold_Italic.ttf')
          })
          font "Tuffy"
          font_size 12
          ini = true
          jpgs.each do |im|
            if ini then
              ini = false
            else
              start_new_page
            end
            text titulo
            w = 550
            h = 700
            bounding_box([0, cursor], :width => w, :height => h) do
              image "#{im}", :fit => [w, h]
              stroke_bounds
            end
          end
        end
      end

      return [titulo, id, texto, urljpg.to_s, urlpdf.to_s, rlocal]
    end

  end
end

app/views/sal7711_gen/articulos/_articulos_categoria.html.erb
<%= f.association :categoriaprensa, 
  collection: Sal7711Gen::Categoriaprensa.habilitados,
  label_method: lambda {|t| t.presenta_nombre },
  value_method: :id,
  input_html: { class: 'chosen-select' }
%>
  

app/views/sal7711_gen/articulos/_articulos_complemento0.erb
<%= f.input :pagina %> 

app/views/sal7711_gen/articulos/_form.html.erb
<%= simple_form_for @articulo, 
  url: modelo_path(@articulo),
  :html => { :class => 'form-horizontal' } do |f| 
%>

  <div class="row">
    <div id="campos" class="offset-sm-0 col-sm-4">
  
      <%= render partial: 'msip/hogar/errores', locals: { f: f } %>

      <% if !f.object || !f.object.id || !f.object.adjunto_file_name %>
        <%= f.input :adjunto, as: :file, label: 'Archivo (.jpg, .png, .tiff)',
          input_html: { "data-imagenpre": 'imagen-detalle'} %>
      <% else %>
        <div class="articulo_adjunto">
          <label for="articulo_attributes_<%=f.object.id%>_adjunto">Archivo</label>
          <a id="articulo_adjunto_attributes_<%=f.object.id%>_adjunto" href="<%= buscar_mostraruno_url(f.object.id) %>", style="text-decoration:none"><%= f.object.adjunto_file_name %></a>
        </div>
      <% end %>
  
      <%= f.input :fecha_localizada, 
        :input_html => { "data-behaviour" => "datepicker"}, 
        :as => :string %>
  
      <%= render partial: 'geo_campos', locals: { f: f } %>
  
      <%= render partial: 'articulos_categoria', locals: { f: f } %>

      <%= f.association :fuenteprensa,
        collection: Msip::Fuenteprensa.habilitados,
        label_method: :nombre, 
        value_method: :id,
        include_blank: false %>
  
      <%= render partial: 'articulos_complemento0', locals: { f: f } %>
  
      <%= render partial: 'articulos_complemento1', locals: { f: f } %>
  
      <%= f.input :texto %> 
  
      <div class="form-actions abajocentrado">
        <%= f.button :submit, class: 'btn btn-primary',
          'data-turbo' => false %>

        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
          modelos_path(@articulo), :class => 'btn' 
        
        %>
      </div>

    </div> <!-- class="offset-sm-0 col-sm-7 col-md-8" -->
  
    <div id="resultados" class="offset-sm-0 col-sm-8">
      <% if f.object && f.object.id && f.object.adjunto_file_name %>
        <%= image_tag url_descarga_jpg(f.object.id), width: "100%", id: 'imagen-detalle' %> 
      <% else %>
        <img src="#" width="100%", id='imagen-detalle'> 
      <% end %>
    </div> <!-- id: resultados -->
  </div> <!-- row -->

<% end %>

app/views/sal7711_gen/articulos/_geo_campos.html.erb
<% paisid = Msip.paisomision ?  Msip.paisomision : 170 %>

<%= f.association :departamento,
  collection: Msip::Departamento.habilitados.
  where(pais_id: paisid),
  label_method: :nombre, 
  value_method: :id 
%>
  <%= f.association :municipio,
    collection: Msip::Municipio.habilitados.joins(:departamento).
    where("msip_departamento.pais_id = ?", paisid),
    label_method: :nombre, 
    value_method: :id
  %>

app/views/sal7711_gen/articulos/edit.html.erb
<%- model_class = Sal7711Gen::Articulo -%>
<div class="page-header">
  <h1><%=t '.title', 
    :default => ["Edita #{model_class.model_name.human.titleize}"] 
    %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sal7711_gen/articulos/new.html.erb
<%- model_class = Sal7711Gen::Articulo-%>
<div class="page-header">
  <h1>
    <%= t '.title', 
      default: ["Nuevo #{model_class.model_name.human.titleize}"]
    %>
  </h1>
</div>
<%= render :partial => 'form' %>

app/views/sal7711_gen/articulos/show.html.erb
<html>
  <head>
    <title><%= @titulo %> </title>
  </head>
  <body>
    <p><%= @titulo %></p>
    <hr>
    <div class="imagen-contenido">
      <% if @descargajgp %>
        <%= image_tag @descargajpg %>
      <% end %>
    </div>
  </body>
</html>